name: Covid19min
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.*
  - numpy=1.19.*
  - pandas=1.1.*
  - plotly=4.10.0
  - python=3.7.*
  - tqdm=4.49.*
  - xlrd=1.2.*
  - pip:
      - tsmoothie==0.1.7
      - uk-covid19==1.2.0
